Repository petercinibulk/envied, pull requests merged in 2023-11, with the labels that each got.

#66 feat: Null Value Support
  examples/envied_example/lib/nullable_env.dart
  examples/envied_example/lib/nullable_env.g.dart
  examples/envied_example/pubspec.lock
  packages/envied/README.md
  packages/envied/lib/src/envied_base.dart
  packages/envied_generator/lib/src/generate_field.dart
  packages/envied_generator/lib/src/generate_field_encrypted.dart
  packages/envied_generator/lib/src/generator.dart
  packages/envied_generator/test/src/generator_tests.dart
Labels: enhancement

#61 chore: fix publish CI
  .github/workflows/publish.yml
Labels: ci/cd

#62 chore: coverage:ignore-file
  examples/envied_example/lib/debug_env.g.dart
  examples/envied_example/lib/env.g.dart
  examples/envied_example/lib/nullable_env.g.dart
  examples/envied_example/lib/release_env.g.dart
  packages/envied_generator/lib/src/generator.dart
  packages/envied_generator/test/src/generator_tests.dart
Labels: enhancement

#70 feat: add Uri and DateTime support
  examples/envied_example/.env
  examples/envied_example/.env_debug
  examples/envied_example/lib/app_env.dart
  examples/envied_example/lib/app_env_fields.dart
  examples/envied_example/lib/debug_env.dart
  examples/envied_example/lib/debug_env.g.dart
  examples/envied_example/lib/env.dart
  examples/envied_example/lib/env.g.dart
  examples/envied_example/lib/nullable_env.g.dart
  examples/envied_example/lib/release_env.dart
  examples/envied_example/lib/release_env.g.dart
  packages/envied_generator/lib/src/extensions.dart
  packages/envied_generator/lib/src/generate_field.dart
  packages/envied_generator/lib/src/generate_field_encrypted.dart
  packages/envied_generator/test/.env.example
  packages/envied_generator/test/src/generator_tests.dart
Labels: enhancement

#72 feat: Obfuscated `double`s and `num`s
  packages/envied/README.md
  packages/envied_generator/lib/src/generate_field_encrypted.dart
  packages/envied_generator/test/.env.example
  packages/envied_generator/test/src/generator_tests.dart
Labels: enhancement

#42 refactor: Adding ability to convert field name from camelCase to CONSTANT_CASE if `varName` is not specified for `@EnvField`
  examples/envied_example/.env
  examples/envied_example/.env_debug
  examples/envied_example/lib/debug_env.dart
  examples/envied_example/lib/env.dart
  examples/envied_example/lib/env.g.dart
  examples/envied_example/lib/example.dart
  examples/envied_example/lib/nullable_env.dart
  examples/envied_example/lib/release_env.dart
  examples/envied_example/lib/release_env.g.dart
  examples/envied_example/pubspec.lock
  packages/envied/lib/src/envied_base.dart
  packages/envied/test/envy_test.dart
  packages/envied_generator/lib/src/generator.dart
  packages/envied_generator/pubspec.yaml
  packages/envied_generator/test/.env.example
  packages/envied_generator/test/src/generator_tests.dart
Labels: enhancement

#73 feat: add Enum support
  examples/envied_example/.env
  examples/envied_example/.env_debug
  examples/envied_example/lib/app_env_fields.dart
  examples/envied_example/lib/constant_case_env.dart
  examples/envied_example/lib/constant_case_env.g.dart
  examples/envied_example/lib/debug_env.dart
  examples/envied_example/lib/debug_env.g.dart
  examples/envied_example/lib/env.dart
  examples/envied_example/lib/env.g.dart
  examples/envied_example/lib/example.dart
  examples/envied_example/lib/example_enum.dart
  examples/envied_example/lib/nullable_env.dart
  examples/envied_example/lib/release_env.dart
  examples/envied_example/lib/release_env.g.dart
  packages/envied_generator/lib/src/extensions.dart
  packages/envied_generator/lib/src/generate_field.dart
  packages/envied_generator/lib/src/generate_field_encrypted.dart
  packages/envied_generator/test/.env.example
  packages/envied_generator/test/src/example_enum.dart
  packages/envied_generator/test/src/generator_tests.dart
Labels: enhancement

#75 chore: add more tests
  packages/envied_generator/test/.env.example
  packages/envied_generator/test/src/generator_tests.dart
Labels: test

#78 chore: update actions/checkout to v4 (was v3)
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci/cd

#76 chore: release v0.5.2
  CHANGELOG.md
  packages/envied/CHANGELOG.md
  packages/envied/pubspec.yaml
  packages/envied_generator/CHANGELOG.md
  packages/envied_generator/pubspec.yaml
Labels: release
